### ISSUE TITLE
CMS examples/tests

### ISSUE THREAD

**Issue by RamseyK** [vbwagner/ctypescrypto#11]
Could examples of using the CMS functions be added? I'm encountering strange crashing issues with using the existing CMS SignedData generation functions. Having tests and proper usage examples would help with this.

Example snippet that crashes on OSX 10.13:

        cert = x509.X509(my_signer_cert)
        pkeyd = pkey.PKey(privkey=my_signer_key, cansign=True)
        certs = [x509.X509(my_ca_cert)]
        sigobj = cms.SignedData.create(data=data, cert=cert,
                                           pkey=pkeyd,
                                           flags=cms.Flags.NOSMIMECAP | cms.Flags.BINARY, certs=certs)

Thanks for all your hard work on this library!

**Comment by vbwagner** [comment]
May be you are just using wrong crypto library? I have reports  that MacOS installs LibreSSL by default, niot OpenSSL. 

Also, when creating pkey objects, you should never specify canSiign explicitely unless you are using black magic and pass there pointer  obtained ftom some other OpenSSL function.  If you pass there PEM or der representation of private key, it should be sett automatically by constructor. Note that this parameter is not documented in the __init__ docstring, and  it is intentiional

Rest should be fiound in openssl documentation.
