### ISSUE TITLE
Load windows DLL named libcrypto-1_1-x64.dll

### ISSUE THREAD

**Issue by alex-eri** [vbwagner/ctypescrypto#12]
Seems fresh packages fow windows here

https://bintray.com/vszakats/generic/openssl

**Comment by vbwagner** [comment]
There are various ways to build openssl. And I don't like idea that my users would download secuity related library from some site with unknown reputation.

Even old sites with established reputation such as sourceforge.net somtimes caught with embedding malware into windows installer..

So I don't recommend to use binary packages from site which claims "Sometihng as a service" and has .com domain.

**Comment by alex-eri** [comment]
This url from official wiki (reopen pls)

https://wiki.openssl.org/index.php/Binaries

**Comment by alex-eri** [comment]
There is no libeay32 of version 1.1...
