### ISSUE TITLE
dll not found if running as administrator or service on windows

### ISSUE THREAD

**Issue by alex-eri** [vbwagner/ctypescrypto#13]
dll not found if running as administrator or service on windows

  File "C:\users\eri\Application Data\Python\Python36\site-packages\ctypescrypto\__init__.py", line 27, in <module>
OSError: Cannot find OpenSSL crypto library

Works if running as user

**Comment by vbwagner** [comment]
One who attempts to run service on Windows, ought to know how to manage PATH environment variable.
It is not ctypescrypto problem, it is your sysytem setup problem.

**Comment by alex-eri** [comment]
DLL in "./"
