### ISSUE TITLE
CMS SignedData.Verify causing SEGFAULT 

### ISSUE THREAD

**Issue by pp185** [vbwagner/ctypescrypto#15]
store = x509.X509Store(cert)
sigobj = cms.SignedData()
sigobj.verify(store=store, data=data, flags=cms.Flags.NOSMIMECAP | cms.Flags.BINARY)

crash @ libcrypto.CMS_verify(self.ptr, certstack, store.store, bio,None, flags)

**Comment by pp185** [comment]
Thank you for your code, anyhelp appreaciated.

**Comment by vbwagner** [comment]
What you are going to verify? You've created empty  SignedData object. There is no signatures  to verify yet.
Of course, it is wrong to segfault in such case. It would be better to raise some meaningful exception.

**Comment by pp185** [comment]
Thankyou for the response. Not very clear in first post. Yes I'm passing signeddata output from create.

Traceback (most recent call last):
  File "t.py", line 9, in <module>
    signer.verify(store, data, cms.Flags.NOSMIMECAP | cms.Flags.BINARY)
  File "/Users/tecg/anaconda2/lib/python2.7/site-packages/ctypescrypto/cms.py", line 177, in verify
    bio_obj = Membio(data)
  File "/Users/tecg/anaconda2/lib/python2.7/site-packages/ctypescrypto/bio.py", line 34, in __init__
    self.bio = libcrypto.BIO_new_mem_buf(c_char_p(data), len(data))
TypeError: object of type 'int' has no len()

**Comment by pp185** [comment]
Thank You. I added flags=cms.Flags.DETACHED | cms.Flags.BINARY in create signed message. And passing pem format data to verify which results in Segmentation fault: 11

**Comment by pp185** [comment]
Thank you for your help. Yes it works for me now.

**Comment by vbwagner** [comment]
Seems to be rather documentation problem, than code
