### ISSUE TITLE
Github release.

### ISSUE THREAD

**Issue by k0ste** [vbwagner/ctypescrypto#16]
Please make a github release, for packaging purposes.
Thanks.

**Comment by vbwagner** [comment]
Done. But what's wrong with getting source from pypi?

**Comment by k0ste** [comment]
I don't see url in README.md. In any case - is a mirror.
Thanks.

**Comment by vbwagner** [comment]
Really python folk doesn't need URL for pypi. They just type pip install module-name.
And no, it is not a mirror. It is repository of releases.
