### ISSUE TITLE
OPENSSL_add_all_algorithms_conf undefined

### ISSUE THREAD

**Issue by alex-eri** [vbwagner/ctypescrypto#7]
New libcrypto breaks lib

AttributeError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: undefined symbol: OPENSSL_add_all_algorithms_conf

**Comment by vbwagner** [comment]
See commit [876630b04080](https://github.com/vbwagner/ctypescrypto/commit/876630b04080b68d724e22066d374ce25efd8a97)
